### PR TITLE
273 target string ablation test fixes

### LINKED ISSUE #273: "Target string" ablation test fixes
The way this is handled is a bit of mess and also broken, because the entire paragraph is suppressed from the prompt, which is important context. We only want to suppress the target string. Implementing this properly should give us a bit of a pattern than we can use for #210. Also the tests run with and without the ablation even in `yarn test` mode, without any visibility on the fact that it is happening or why except that each test case can be seen to run twice.

- [ ] Option not to run ablation test(s) in `yarn test` mode
- [ ] Mutating `add-expected-value` inside 
- [ ] Revisit `Program.toUserPrompt()` and `Paragraph.toFluidSyntax()`

### PR DESCRIPTION
**Pull request by alfy91**

### CODE REVIEW

File: src/main/java/authoringassistant/Program.java [hunk 1]
```diff
@@ -203,20 +205,45 @@ public static ArrayList<Program> loadPrograms(String casesFolder) throws IOExcep
...
+            } else {
+                programs.add(new Program(
+                        paragraphFromJSON(testCase.getJSONArray("paragraph"), datasets, testVariables, imports, replaceVariables(code, variables), casePath, false),
+                        datasets,
+                        imports,
+                        replaceVariables(code, variables),
+                        loadDatasetFiles(datasets, expandVariables(tv, null)),
+                        casePath,
+                        test_configurations,
+                        false
```
Comment (rolyp) [inline src/main/java/authoringassistant/Program.java]: This looks wrong Alfonso -- setting `Program.targetValue` to `false` will cause `toFluidSyntax` to omit (ablate) the target value, no? (Whereas in this case we want to generate it.)

Suggestions:
- Align name and meaning of `Program.targetValue` with the `ablate-target-value` setting, so there is less room for confusion. (That will mean renaming the former and inverting its meaning in `toFluidSyntax`.)
- Remove the duplicated code here so there is less room for things to go wrong.

**Review by rolyp — APPROVED** [review]

**Review by rolyp — CHANGES_REQUESTED** [review]
Are you sure this is correct Alfonso? It looks like the test runs are omitting the target value, even though `ablate-target-value` is `false`.

See comments above.

File: settings/default.json [hunk 2]
```diff
@@ -11,6 +11,6 @@
   "authoring-agent-class": null,
   "suggestion-agent-class": null,
   "truncate-tests-at": -1,
-  "target-value": false
+  "ablate-target-value": false
```
Comment (rolyp) [inline settings/default.json:14]: This default value makes sense now (if it were `target-value`, then the default should have been `true`).

File: src/main/java/authoringassistant/Program.java [hunk 3]
```diff
@@ -205,24 +205,24 @@ public static ArrayList<Program> loadPrograms(String casesFolder) throws IOExcep
                     .mapToObj(json_imports::getString)
                     .toList();
             
-            boolean[] targetValues = Settings.hasTargetValue() ? new boolean[]{true} : new boolean[]{true, false};
-            for (boolean targetValue : targetValues) {
+            boolean[] ablateTargetValues = Settings.isAblateTargetValue() ? new boolean[]{true} : new boolean[]{true, false};
```
Comment (rolyp) [inline src/main/java/authoringassistant/Program.java]: The baseline value should be `false`, I think (i.e. don't ablate).

I'd write this code slightly differently, to make it clearer which is the baseline setting (since confusion seems to be order of the day here):

```java
List<Boolean> ablateTargetValues = new ArrayList<>(List.of(false));
if (Settings.isAblateTargetValue()) {
    ablateTargetValues.add(true);
}
for (boolean ablateTargetValue : ablateTargetValues) {
   ...
}
```
This makes more explicit that we always run the `false` (no ablation) experiment, and optionally add the ablation experiment.

File: results/test/gpt-5-mini/scigen-manual/results.csv [hunk 4]
```diff
@@ -0,0 +1,35 @@
+run;test-case;problem-no;llm-agent;target-value-present;categories;fails-interpreter;fails-counterfactual;fails-no-response;fails-literal
```
Comment (rolyp) [inline results/test/gpt-5-mini/scigen-manual/results.csv:1]: `target-value-present` should rename to `ablate-target-value` (checking whether `generate-charts.py` needs a similar renaming)

File: src/main/java/authoringassistant/SuggestionAgent.java [hunk 5]
```diff
@@ -53,7 +53,7 @@ public SuggestionAgentResult generateTemplateProgram(Program p) throws IOExcepti
                     prompts.addUserMessage("Your response contains extra text outside the annotated paragraph. Please provide ONLY the original text with [REPLACE value=\"...\" categories=\"...\"] annotations inserted inline. Do not add any explanations, comments, markdown formatting, or other additional content.");
                     continue;
                 }
-                return new SuggestionAgentResult(new Program(paragraph, p.getDatasetFilenames(),p.getImports(),p.getCode(),p.get_loadedDatasets(),p.getTestCasePath(),p.getDatasetsVariants()), attempts);
+                return new SuggestionAgentResult(new Program(paragraph, p.getDatasetFilenames(),p.getImports(),p.getCode(),p.get_loadedDatasets(),p.getTestCasePath(),p.getDatasetsVariants(), true), attempts);
```
Comment (rolyp) [inline src/main/java/authoringassistant/SuggestionAgent.java]: And `true` here should revert to `false`, right?

File: src/main/java/authoringassistant/paragraph/Paragraph.java [hunk 6]
```diff
@@ -13,21 +13,32 @@ public class Paragraph extends ArrayList<TextFragment> {
     public Paragraph() {
     }
 
-    public String toFluidSyntax(boolean onlyValue) {
+    public String toFluidSyntax(boolean addExpectedValue) {
```
Comment (rolyp) [inline src/main/java/authoringassistant/paragraph/Paragraph.java]: This should be called `ablateExpectedValue` and its meaning should be inverted

File: src/main/java/authoringassistant/paragraph/Paragraph.java [hunk 7]
```diff
@@ -13,21 +13,32 @@ public class Paragraph extends ArrayList<TextFragment> {
...
-                    return (STR."${\{e_.getExpr()}}");
-                } else if (Settings.isAddExpectedValue()) {
+                return (STR."${\{e_.getExpr()}}");
+            } else {
+                throw new RuntimeException("Literal or expression expected.");
+            }
+        }).collect(Collectors.joining(" "))}\n\"\"\"";
+    }
+
+    public String toParagraphValue(boolean addExpectedValue) {
```
Comment (rolyp) [inline src/main/java/authoringassistant/paragraph/Paragraph.java]: Ditto

**Review by rolyp — CHANGES_REQUESTED** [review]
Thanks, still severals places left though where the boolean signs are incorrect or interpreted incorrectly, as you can see from the `logs` output.

**Review by rolyp — APPROVED** [review]
